package com.triquang.entity;
// Generated Jun 14, 2022, 10:00:37 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Benhnhan generated by hbm2java
 */
@Entity
@Table(name = "benhnhan", catalog = "datlichkhambenh")
@NamedQueries({
	@NamedQuery(name = "Benhnhan.findAll", query = "SELECT b FROM Benhnhan b ORDER BY b.tenbn"),
	@NamedQuery(name = "Benhnhan.countAll", query = "SELECT COUNT(*) FROM Benhnhan"),
	@NamedQuery(name = "Benhnhan.findByName", query = "SELECT b FROM Benhnhan b WHERE b.tenbn = :name")
})
public class Benhnhan implements java.io.Serializable {

	private Integer mabn;
	private String tenbn;
	private Date ngaysinh;
	private String gioitinh;
	private Set<Lichkham> lichkhams = new HashSet<Lichkham>(0);

	public Benhnhan() {
	}
	
	public Benhnhan(String tenbn) {
		this.tenbn = tenbn;
	}

	public Benhnhan(String tenbn, Date ngaysinh, String gioitinh) {
		this.tenbn = tenbn;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
	}

	public Benhnhan(String tenbn, Date ngaysinh, String gioitinh, Set<Lichkham> lichkhams) {
		this.tenbn = tenbn;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
		this.lichkhams = lichkhams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mabn", unique = true, nullable = false)
	public Integer getMabn() {
		return this.mabn;
	}

	public void setMabn(Integer mabn) {
		this.mabn = mabn;
	}

	@Column(name = "tenbn", nullable = false, length = 45)
	public String getTenbn() {
		return this.tenbn;
	}

	public void setTenbn(String tenbn) {
		this.tenbn = tenbn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", nullable = false, length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "gioitinh", nullable = false, length = 20)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benhnhan")
	public Set<Lichkham> getLichkhams() {
		return this.lichkhams;
	}

	public void setLichkhams(Set<Lichkham> lichkhams) {
		this.lichkhams = lichkhams;
	}

}
