package com.triquang.entity;
// Generated Jun 14, 2022, 10:00:37 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khoa generated by hbm2java
 */
@Entity
@Table(name = "khoa", catalog = "datlichkhambenh")
@NamedQueries({
	@NamedQuery(name = "Khoa.findAll", query = "SELECT k FROM Khoa k ORDER BY k.tenkhoa"),
	@NamedQuery(name = "Khoa.countAll", query = "SELECT COUNT(*) FROM Khoa"),
	@NamedQuery(name = "Khoa.findByName", query = "SELECT k FROM Khoa k WHERE k.tenkhoa = :name")
})
public class Khoa implements java.io.Serializable {

	private Integer makhoa;
	private String tenkhoa;
	private Set<Bacsi> bacsis = new HashSet<Bacsi>(0);

	public Khoa() {
	}

	public Khoa(String tenkhoa) {
		this.tenkhoa = tenkhoa;
	}

	public Khoa(String tenkhoa, Set<Bacsi> bacsis) {
		this.tenkhoa = tenkhoa;
		this.bacsis = bacsis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "makhoa", unique = true, nullable = false)
	public Integer getMakhoa() {
		return this.makhoa;
	}

	public void setMakhoa(Integer makhoa) {
		this.makhoa = makhoa;
	}

	@Column(name = "tenkhoa", nullable = false, length = 45)
	public String getTenkhoa() {
		return this.tenkhoa;
	}

	public void setTenkhoa(String tenkhoa) {
		this.tenkhoa = tenkhoa;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "khoa")
	public Set<Bacsi> getBacsis() {
		return this.bacsis;
	}

	public void setBacsis(Set<Bacsi> bacsis) {
		this.bacsis = bacsis;
	}

}
