package com.triquang.entity;
// Generated Jun 14, 2022, 10:00:37 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Lichkham generated by hbm2java
 */
@Entity
@Table(name = "lichkham", catalog = "datlichkhambenh", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
@NamedQueries({ @NamedQuery(name = "Lichkham.findAll", query = "SELECT l FROM Lichkham l"),
		@NamedQuery(name = "Lichkham.findByTitle", query = "SELECT l FROM Lichkham l WHERE l.title = :title"),
		@NamedQuery(name = "Lichkham.countAll", query = "SELECT COUNT(*) FROM Lichkham l"),
		@NamedQuery(name = "Lichkham.countBySchedule", query = "SELECT COUNT(l) FROM Lichkham l "
				+ "WHERE l.bacsi.mabs = :docId"),
		@NamedQuery(name = "Lichkham.findByDoctor", query = "SELECT l FROM Lichkham l JOIN "
				+ "Bacsi b ON l.bacsi.mabs = b.mabs AND b.mabs = :docId"),
		@NamedQuery(name = "Lichkham.listNew", query = "SELECT l FROM Lichkham l ORDER BY l.ngaykham DESC"),
		@NamedQuery(name = "Lichkham.search", query = "SELECT l FROM Lichkham l WHERE l.title LIKE '%' || :keyword || '%'"
				+ " OR l.noidung LIKE '%' || :keyword || '%'") })
public class Lichkham implements java.io.Serializable {

	private Integer id;
	private Bacsi bacsi;
	private Benhnhan benhnhan;
	private Date ngaykham;
	private String noidung;
	private String title;

	public Lichkham() {
	}

	public Lichkham(Bacsi bacsi, Benhnhan benhnhan, String title, Date ngaykham, String noidung) {
		this.bacsi = bacsi;
		this.benhnhan = benhnhan;
		this.ngaykham = ngaykham;
		this.noidung = noidung;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", unique = true, nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mabs", nullable = false)
	public Bacsi getBacsi() {
		return this.bacsi;
	}

	public void setBacsi(Bacsi bacsi) {
		this.bacsi = bacsi;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mabn", nullable = false)
	public Benhnhan getBenhnhan() {
		return this.benhnhan;
	}

	public void setBenhnhan(Benhnhan benhnhan) {
		this.benhnhan = benhnhan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaykham", nullable = false, length = 10)
	public Date getNgaykham() {
		return this.ngaykham;
	}

	public void setNgaykham(Date ngaykham) {
		this.ngaykham = ngaykham;
	}

	@Column(name = "noidung", nullable = false, length = 16777215)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Override
	public int hashCode() {
		return Objects.hash(bacsi, benhnhan, id, ngaykham, noidung);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lichkham other = (Lichkham) obj;
		return Objects.equals(bacsi, other.bacsi) && Objects.equals(benhnhan, other.benhnhan)
				&& Objects.equals(id, other.id) && Objects.equals(ngaykham, other.ngaykham)
				&& Objects.equals(noidung, other.noidung);
	}

}
